blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

post/urls.py
from django.urls import path

from post.views import PostsListView

urlpatterns = [
    path('posts/', PostsListView.as_view(), name="posts"),
]

post/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=500)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']


class Gallery(models.Model):
    title = models.CharField(max_length=500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']


class Photo(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    photo_url = models.URLField()

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

post/views.py
from django.shortcuts import render

from django.views.generic import ListView

from post.filters import PostFilter
from post.models import Post


class PostsListView(ListView):
    model = Post

    def get(self, request, *args, **kwargs):
        f = PostFilter(request.GET, queryset=self.queryset)
        self.extra_context = {"filter": f}
        return super().get(request, *args, **kwargs)

templates/post/post_list.html
{% extends 'admin/base.html' %}

{% block content %}
    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit">Search</button>
    </form>

    <table>
        <tr>
            <td>Id</td>
            <td>title</td>
            <td>content</td>
            <td>created</td>
            <td>author</td>
        </tr>
        {% for object in filter.qs %}
            <tr>
                <td>{{ object.id }}</td>
                <td>{{ object.title }}</td>
                <td>{{ object.content|slice:100 }}...</td>
                <td>{{ object.created_at|date }}
                    at {{ object.created_at|time }}</td>
                <td>{{ object.author.get_full_name }}</td>
            </tr>
            {% for g in object.gallery_set.all %}
                <tr>
                    <td>title</td>
                    <td>desc</td>
                    <td>created</td>
                    <td>photos count</td>
                </tr>
                <tr>
                    <td>{{ g.title }}</td>
                    <td>{{ g.description }}</td>
                    <td>{{ g.created_at }}</td>
                    <td>{{ g.photo_set.count }}</td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>
{% endblock %}